config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'posts#index'
  resources :categories do
    resources :posts
    resources :comments, only: %i[create destroy], module: :categories
  end
  resources :posts, only: %i[show index] do
    resources :comments, only: %i[create destroy], module: :posts
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new(role: 'guest')

    if user.role?(:admin)
      can :manage, :all
    elsif user.role?(:regular)
      can :delete, Comment, user_id: user.id
      can :create, Comment
    end
    can :read, Post
    can :read, Category
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint(8)        not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_categories_on_name  (name) UNIQUE
#

class Category < ApplicationRecord
  include Concerns::Commentable

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates_with NameValidator

  has_many :posts, dependent: :destroy
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :bigint(8)        not null, primary key
#  commentable_type :string
#  content          :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_id   :bigint(8)
#  user_id          :bigint(8)
#
# Indexes
#
#  index_comments_on_commentable_type_and_commentable_id  (commentable_type,commentable_id)
#  index_comments_on_user_id                              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 400 }
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  def author
    user.full_name
  end
end

app/models/concerns/commentable.rb
module Concerns
  module Commentable
    extend ActiveSupport::Concern

    included do
      has_many :comments, as: :commentable, dependent: :delete_all
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint(8)        not null, primary key
#  content     :text
#  file        :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint(8)
#
# Indexes
#
#  index_posts_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

class Post < ApplicationRecord
  include Concerns::Commentable

  validates :name, presence: true, length: { maximum: 100 }
  validates_with NameValidator
  validate :max_file_size

  belongs_to :category

  mount_uploader :file, FileUploader

  private

  def max_file_size
    errors[:file] << 'file size can not be more than 2 megabytes.' if file.size > 2.megabytes
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :bigint(8)        not null, primary key
#  email              :string           default(""), not null
#  encrypted_password :string           default(""), not null
#  first_name         :string
#  last_name          :string
#  role               :string           default("regular")
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable

  before_create :format_names
  before_update :format_names
  validates :first_name, presence: true, length: { in: 2..50 }
  validates :last_name, presence: true, length: { in: 2..50 }

  has_many :comments, dependent: :destroy
  def name
    first_name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def role?(tested_role)
    role == tested_role.to_s
  end

  private

  def format_names
    first_name[0] = first_name[0].upcase if first_name
    last_name[0] = last_name[0].upcase if last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    render file: "#{Rails.root}/public/403", formats: [:html], status: 403,
           layout: false
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name role])
  end
end

app/controllers/categories/comments_controller.rb
class Categories::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Category.find(params[:category_id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  authorize_resource

  def show
    @category = Category.find(params[:id])
  end

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_path(@category), notice: 'New category created!'
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to @category, notice: 'Successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    Category.destroy(params[:id])
    redirect_to categories_path, notice: 'Successfully deleted!'
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user
    authorize! :create, @comment
    if @comment.save
      comment_html = render_to_string(template: 'comments/_comment', layout: false,
                                      locals: { comment: @comment })
      render json: { comment: comment_html }
    else
      error_msg = "Comment content #{@comment.errors.messages[:content].first}."
      render json: { error: error_msg }, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    authorize! :delete, @comment
    @comment.destroy
    render json: { comment_id: @comment.id }
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # TODO: add styles to view
  # TODO: implement pagination
  authorize_resource

  def index
    @posts = fetch_posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.category_id = params[:category_id]
    if @post.save
      redirect_to @post, notice: 'Post successfully created!'
    else
      pp @post.errors.messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post, notice: 'Post successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to category_posts_path(@post.category_id), notice: 'Post successfully deleted!'
  end

  private

  def fetch_posts
    if params[:category_id]
      Post.where(category_id: params[:category_id])
    else
      Post.all
    end
  end

  def post_params
    params.require(:post).permit(:name, :content, :file, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_category.html.erb
<div class="card">
  <div class="card-title">
    <h2 class="ml-3 mt-2"><%= category.name %></h2>
  </div>
  <div class="card-body">
    <div>
      <%= category.description %>
    </div>
    <%= link_to 'Show more', category_path(category) %>
    <div class="statistic">
      Comments: <%= category.comments.count %> |
      Posts:
      <% if category.posts.count != 0 %>
        <%= link_to category_posts_path(category) do %>
          <%= category.posts.count %>
        <% end %>
      <% else %>
        Posts: <%= category.posts.count %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name, value: @category.name %>
  <%= f.input :description, value: @category.description %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit "<%= @category.name == '' ? @category.name_was : @category.name %>" category</h2>

<%= render 'categories/form' %>

app/views/categories/index.html.erb
<div class="col-lg-8 offset-lg-2">
  <% if @categories.empty? %>
    <span>Created categories will be displayed here!</span>
  <% else %>
    <%= render @categories %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'categories/form' %>

app/views/categories/show.html.erb
<div class="category">
  <h1 class="category_name"><%= @category.name %></h1>
  <div class="category_description">
    <%= @category.description %>
  </div>
  <%= link_to 'Show related posts', category_posts_path(@category) %>
  <% if can? :manage, @category %>
    | <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Delete', @category, method: :delete,
                data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Add post', new_category_post_path(@category) %>
  <% end %>
  <h4 class="text-center">Comments</h4>
  <%= render partial: 'comments/comments_section', locals: { commentable: @category } %>
</div>

app/views/comments/_comment.html.erb
<div class="comment card pl-2 my-2" id="comment_<%= comment.id %>">
  <p class="mt-3"><%= comment.content %></p>
  <div>
    <hr>
    Posted by: <b><%= comment.user.full_name %></b> |
    <span>
    <%= link_to 'Delete', polymorphic_path([comment.commentable, comment]), method: :delete,
                class: 'delete_comment', remote: true,
                data: { comment_id: comment.id } if can? :delete, comment %>
  </span>
  </div>
</div>

app/views/comments/_comments_section.html.erb
<div id="comments_section">
  <div id="comments">
    <%= render partial: 'comments/comment', collection: commentable.comments.last(4) %>
  </div>
  <% if can? :create, Comment %>
    <%= render partial: 'comments/form', locals: { commentable: commentable } %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new], remote: true do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "Add a comment..." %>
    <div class="invalid-feedback"></div>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <div class="navbar-nav">
      <%= link_to 'Categories', categories_path, class: 'nav-item nav-link' %>
      <%= link_to 'Add category', new_category_path, class: 'nav-item nav-link' %>
      <%= link_to 'Posts', posts_path, class: 'nav-item nav-link' %>
    </div>
  </div>
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="mt-3">Hello, <%= current_user.full_name %>!</li>
      <li class="nav-item mx-2">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-block my-2' %>
      </li>
    <% else %>
      <li class="nav-item mx-2">
        <%= link_to 'Log in', new_user_session_path, class: 'btn btn-secondary btn-block my-2' %>
      </li>
      <li class="nav-item mx-2">
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-block my-2' %>
      </li>
    <% end %>
  </ul>
</nav>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for [:category, @post] do |f| %>
  <%= f.input :name, value: @post.name %>
  <%= f.input :content, value: @post.content %>
  <%= f.input :file, as: :file %>
  <% unless @post.file.url.nil? %>
    <div class="attachement">
      <%= link_to @post.file.file.filename, @post.file.url, target: :blank %>
      <span class="attachment_size">
        (<%= @post.file.size / 1.kilobyte %> kb.)
      </span>
    </div>
  <% end %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div class="post_short">
  <h3><%= post.name %></h3>
  <div class="post_preview">
    <%= truncate(post.content, length: 200) { link_to 'Read', post_path(post) } %>
  </div>
  <hr>
  <span>Comments: <%= post.comments.count %></span> |
  <% if post.file.url.nil? %>
    <span>(without files)</span>
  <% else %>
    <div class="post_attachment">
      <%= link_to post.file.file.filename, post.file.url, target: :blank %>
      <span class="attachment_size">
        (<%= post.file.size / 1.kilobyte %> kb.)
      </span>
    </div>
  <% end %>
  <hr>
</div>

app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= render 'posts/form' %>

app/views/posts/index.html.erb
<div class="col-lg-8 offset-lg-2">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<div class="post">
  <h1><%= @post.name %></h1>
  <% if can? :manage, @post %>
    <%= link_to 'Edit', edit_category_post_path(@post) %> |
    <%= link_to 'Delete', category_post_path(@post), method: :delete,
                data: { confirm: 'Are you sure?' } %>
    <hr>
  <% end %>
  <div class="post_content">
    <%= @post.content %>
  </div>
  <% unless @post.file.url.nil? %>
    <div class="post_attachment">
      <%= link_to @post.file.file.filename, @post.file.url, target: :blank %>
      <span class="attachment_size">
        (<%= @post.file.size / 1.kilobyte %> kb.)
      </span>
    </div>
  <% end %>
  <hr>
  <h4 class="text-center">Comments</h4>
  <%= render partial: 'comments/comments_section', locals: { commentable: @post } %>
</div>